### ISSUE TITLE
Rename repo from `python-directory-sync-example` to `python-flask-dsync-example`

### ISSUE THREAD

**Issue by erin-workos** [workos-inc/python-directory-sync-example#1]
Could we rename this repo from `python-directory-sync-example `to `python-flask-dsync-example`? I'm developing a `python-django-dsync-example` app and would like to have the web frameworks present in the repo name.

Similar to this issue in a related repo:
https://github.com/workos-inc/python-flask-sso-example/issues/4

**Comment by marktran** [comment]
@erin-workos I'm going to name it `python-flask-directory-sync-example` instead. We haven't really standardized on the `dsync` shorthand and are trying to remove it in some places.

**Comment by erin-workos** [comment]
Works for me, thanks!
